version: "3.9"
services:
  db:
    image: mariadb:10.9.3
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    env_file:
      - .env
  adminer:
    image: adminer
    restart: always
    ports:
      - "9999:8080"